# Это базовый рабочий процесс, который поможет вам начать работу с Действиями.

Имя: ци

# Контролирует, когда будет запускаться рабочий процесс
на:
  # Запускает рабочий процесс при событиях запроса push или pull, но только для «основной» ветки.
  толкать:
    Ветви: [ "основной" ]
  pull_request:
    Ветви: [ "основной" ]

  # Позволяет запускать этот рабочий процесс вручную на вкладке «Действия».
  workflow_dispatch:

# Выполнение рабочего процесса состоит из одного или нескольких заданий, которые могут выполняться последовательно или параллельно.
рабочие места:
  # Этот рабочий процесс содержит одно задание под названием «сборка"
  построить:
    # Тип бегуна, на котором будет выполняться задание
    наезд: Ubuntu-последний

    # Шаги представляют собой последовательность задач, которые будут выполняться в рамках задания.
    шаги:
      # Извлекает ваш репозиторий в $GITHUB_WORKSPACE, чтобы ваша работа могла получить к нему доступ.
      - использует: действия/checkout@v4

      # Запускает одну команду с использованием оболочки бегунов
      - Имя: Запуск однострочного скрипта
        бегать: эхо Привет, мир!

      # Запускает набор команд с использованием оболочки бегунов.
      - Имя: Запуск многострочного скрипта
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
